language: python

python:
  - "2.7"
  - "3.5"

compiler:
  - gcc

virtualenv:
  system_site_packages: true

before_install:
  # Fetch and install conda
  # -----------------------
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
  - pip install --user coveralls
  - mv ${HOME}/.local/bin/coveralls ${HOME}/.local/bin/coveralls-py
  - pip install --user cpp-coveralls
  - mv ${HOME}/.local/bin/coveralls ${HOME}/.local/bin/coveralls-cpp

install:
  # Install and test
  - CFLAGS="-fprofile-arcs -ftest-coverage" make -j2

script:
  - OMP_NUM_THREADS=1 coverage run setup.py test
  - OMP_NUM_THREADS=4 coverage run setup.py test

after_success: 
  - coveralls-cpp
  - coveralls-py

